version: '2'
services:
  simplesamlphp:
    build: ./simplesamlphp/
    restart: always
    hostname: simplesamlphp
    container_name: simplesamlphp
    restart: always
    expose:
     - 80
    environment:
     - VIRTUAL_HOST=lt.eap.litnet.lt
     - LETSENCRYPT_HOST=lt.eap.litnet.lt
     - LETSENCRYPT_EMAIL=admins-linux@litnet.lt
    volumes:
     - /simplesamlphp
  php:
    build: ./fpm/
    hostname: php-fpm
    container_name: php-fpm
    expose:
     - "9000"
    volumes_from:
     - simplesamlphp
  memcache-server:
    hostname: memcache-server
    container_name: memcache-server
    image: memcached
    expose:
     - "11211"
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    hostname: nginx-proxy
    restart: always
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - /srv/nginx/certs/:/etc/nginx/certs
     - /etc/nginx/conf.d
     - /etc/nginx/vhost.d
     - /usr/share/nginx/html
    labels:
     - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    environment:
     - DEFAULT_HOST=lt.eap.litnet.lt
  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    hostname: letsencrypt
    restart: always
    volumes_from:
     - nginx-proxy
    volumes:
     - /srv/nginx/certs/:/etc/nginx/certs:rw
     - /var/run/docker.sock:/var/run/docker.sock:ro
